# This is a basic workflow to help you get started with Actions
name: Auto commit

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  
  push:
    branches:
      - main
  schedule:
    - cron: "0 7,10,13,19,22 * * *" #https://crontab.guru/#0_7,10,13,19,22_*_*_*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  auto_green:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      
      - uses: actions/checkout@v3      
        with:
         persist-credentials: false
         fetch-depth: 0

      # Runs a single command using the runners shell
      - name: Modify LAST_UPDATED File
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
      - name: Commit changes
        run: |
          git config --local user.email "sholehud10@gmail.com"
          git config --local user.name "Sholehud10"
          git add -A
          git commit -m "Updating ..."
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          force: true
          directory: '.'
          github_token: ${{ secrets.GITHUB_TOKEN }}
